id:         212997
queryURL:   http://folding.extremeoverclocking.com/xml/team_summary.php?t=
bgImage: background.png

statConfigs:
  - key:  Team_Name
    name: Team
    color:
        r: 1.0
        g: 1.0
        b: 1.0
        a: 1.0
    position:
        x: 8
        y: 24

  - key:  Rank
    name: Rank
    color:
        r: 1.0
        g: 1.0
        b: 1.0
        a: 1.0
    position:
        x: 8
        y: 48

